CREATE DATABASE QUANLIBANHANG
GO

USE QUANLIBANHANG
GO



--TABLE
CREATE TABLE ATABLE
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100),
	STATUS NVARCHAR(100) 

)
GO

--FOODCATEGORY
CREATE TABLE FOODCATEGORY
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL,
	
 )
GO
--FOOD
CREATE TABLE FOOD
(	
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100),
	IDCATEGORY INT FOREIGN KEY (IDCATEGORY) REFERENCES FOODCATEGORY(ID),
	PRICE int DEFAULT 0
)
GO
--ACCOUNT
CREATE TABLE ACCOUNT 
(
	USERNAME NVARCHAR(50) NOT NULL PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL DEFAULT 'VANG LAI',
	PASSWORD NVARCHAR(500) DEFAULT 0 NOT NULL,
	KINDOFACC INT NOT NULL
)
GO

--BILL
CREATE TABLE BILL
(
	ID INT IDENTITY PRIMARY KEY,
	DATECHECKIN DATE NOT NULL DEFAULT GETDATE(),
	DATECHECKOUT DATE DEFAULT NULL,
	IDTABLE INT NOT NULL FOREIGN KEY (IDTABLE) REFERENCES ATABLE(ID),
	ISPAID INT NOT NULL,
	TOTALPRICE int DEFAULT 0
)
go
--BILLINFO
CREATE TABLE BILLINFO
(
	ID INT IDENTITY PRIMARY KEY,
	IDBILL INT NOT NULL FOREIGN KEY(IDBILL) REFERENCES BILL(ID),
	IDFOOD INT NOT NULL FOREIGN KEY (IDFOOD) REFERENCES FOOD(ID),
	SOLUONG INT NOT NULL DEFAULT 0
)
GO


--Tạo Bàn
INSERT INTO ATABLE VALUES (N'BÀN 1', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 2', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 3', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 4', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 5', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 6', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 7', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 8', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 9', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 10', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 11', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 12', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 13', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 14', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 15', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 16', N'TRỐNG')
GO

--TAO CATAGORY
INSERT INTO FOODCATEGORY VALUES(N'Hải Sản')
INSERT INTO FOODCATEGORY VALUES(N'Trên Cạn')
INSERT INTO FOODCATEGORY VALUES(N'Nông Sản và Trái Cây')
INSERT INTO FOODCATEGORY VALUES(N'Thức Uống')

GO
-- THEM MON AN


---them nuoc uong
INSERT INTO FOOD VALUES(N'Nước Mía','4','5000')
INSERT INTO FOOD VALUES(N'Compact','4','8000')
INSERT INTO FOOD VALUES(N'Nước Dừa','4','9000')
INSERT INTO FOOD VALUES(N'Trà đá','4','4000')
INSERT INTO FOOD VALUES(N'Trà Đào','4','10000')
INSERT INTO FOOD VALUES(N'Nước Cam','4','10000')
INSERT INTO FOOD VALUES(N'Nước Ngọt','4','7000')
INSERT INTO FOOD VALUES(N'Cà Phê','4','7000')
INSERT INTO FOOD VALUES(N'Cà Phê','4','7000')
GO
--them hải sản
INSERT INTO FOOD VALUES(N'Cá Ba Sa Kho','1','100000')
INSERT INTO FOOD VALUES(N'Mực Hấp Gừng','1','220000')
INSERT INTO FOOD VALUES(N'Mực nướng','1','200000')
INSERT INTO FOOD VALUES(N'Cá Hồi Áp Chảo','1','250000')
INSERT INTO FOOD VALUES(N'Ốc Hương Nha Trang','1','250000')
INSERT INTO FOOD VALUES(N'Cá Hồi Áp Chảo','1','250000')
INSERT INTO FOOD VALUES(N'Cua Năm Căn Cà Mau','1','450000')
INSERT INTO FOOD VALUES(N'Bào Ngư Bạch Long Vĩ','1','950000')
GO
--Them trên cạn

INSERT INTO FOOD VALUES(N'Gà Đốt','2','250000')
INSERT INTO FOOD VALUES(N'Gà hấp Lá Chúc','2','200000')
INSERT INTO FOOD VALUES(N'Gà Chiên Nước Mắm','2','180000')
INSERT INTO FOOD VALUES(N'Gà Nướng Muối Ớt','2','170000')
INSERT INTO FOOD VALUES(N'Gà Hấp Rượu','2','230000')
INSERT INTO FOOD VALUES(N'Bò Nướng Lá Lốt','2','290000')
INSERT INTO FOOD VALUES(N'Bò Lúc Lắc','2','240000')
GO
--them nong san
INSERT INTO FOOD VALUES(N'Khoai Mì Nướng','3','8000')
INSERT INTO FOOD VALUES(N'Ổi','3','7000')
INSERT INTO FOOD VALUES(N'Chuối nướng','3','12000')
INSERT INTO FOOD VALUES(N'Gỏi Đu Đủ','3','15000')
INSERT INTO FOOD VALUES(N'Khoay Tây Chiên ','3','10000')
INSERT INTO FOOD VALUES(N'Bánh Gạo Nếp','3','10000')
INSERT INTO FOOD VALUES(N'Khoai Mỡ Chiên','3','10000')
INSERT INTO FOOD VALUES(N'Khoai Lang Nướng','3','10000')
GO

--TAI KHOAN MAC DINH
INSERT INTO ACCOUNT VALUES('ADMIN','ADMIN','ADMIN','1')
INSERT INTO ACCOUNT VALUES('STAFF','STAFF','0','2')
GO

CREATE PROC USP_insertBillinfo
@idbill int, @idfood int,@count int
AS
BEGIN 
	DECLARE @isEXSISTBILLINFO INT
	DECLARE @foodCount INT
	SELECT @isEXSISTBILLINFO =ID FROM BILLINFO WHERE IDBILL=@idbill AND IDFOOD=@idfood
	SELECT @foodCount=SOLUONG FROM BILLINFO WHERE IDBILL=@idbill AND IDFOOD=@idfood
	DECLARE @FOODPRICE INT
	SELECT @FOODPRICE=PRICE FROM FOOD WHERE ID=@idfood
	IF(@isEXSISTBILLINFO>0)
		BEGIN
		DECLARE @TEMPCOUNT INT =@FOODCOUNT+@COUNT
		IF(@TEMPCOUNT>0)
		BEGIN
			UPDATE BILLINFO SET SOLUONG=@TEMPCOUNT WHERE IDBILL=@IDBILL AND IDFOOD=@idfood
			UPDATE BILL SET TOTALPRICE=TOTALPRICE+(@count*@FOODPRICE)
		END
		ELSE
		BEGIN
			DELETE BILLINFO WHERE  IDBILL=@IDBILL AND IDFOOD=@idfood
		END
		END
	ELSE
	BEGIN
	IF(@count <=0)
		BEGIN
		RETURN 1;
		END
	ELSE
	BEGIN
	INSERT BILLINFO VALUES (@idbill,@idfood,@count)
	UPDATE BILL SET TOTALPRICE=TOTALPRICE+@FOODPRICE
	END
	END
END
GO



CREATE TRIGGER UPDATEBILLINFO
ON BILLINFO FOR INSERT, UPDATE
AS 
BEGIN
	DECLARE @IDBILL INT
	SELECT @IDBILL=IDBILL FROM inserted


	DECLARE @IDTABLE INT
	SELECT @IDTABLE=IDTABLE FROM BILL WHERE ID=@IDBILL AND ISPAID=0
	
	UPDATE ATABLE SET STATUS=N'CÓ NGƯỜI' WHERE ID=@IDTABLE


END
GO

CREATE TRIGGER DELETEBILLINFO
ON BILLINFO FOR DELETE
AS
BEGIN
	DECLARE @IDBILLINFO INT, @IDBILL INT
	SELECT @IDBILLINFO=ID,@IDBILL =IDBILL FROM deleted

	DECLARE @IDTABLE INT
	SELECT @IDTABLE=IDTABLE  FROM BILL WHERE ID=@IDBILL AND ISPAID=0

	DECLARE @COUNT INT
	SELECT @COUNT=COUNT(*) FROM BILLINFO AS BI , BILL AS B WHERE B.ID=@IDBILL AND B.ISPAID=0 AND BI.IDBILL=@IDBILL

	IF(@COUNT = 0)
		UPDATE ATABLE SET STATUS= N'TRỐNG' WHERE ID=@IDTABLE
END
GO






CREATE TRIGGER UPDATEBILL ON BILL
FOR UPDATE
AS
BEGIN
	DECLARE @IDBILL INT
	SELECT @IDBILL=ID FROM inserted

	DECLARE @IDTABLE INT
	SELECT @IDTABLE=IDTABLE FROM BILL WHERE ID=@IDBILL

	DECLARE @COUNT INT=0
	SELECT @COUNT=COUNT(*) FROM BILL WHERE IDTABLE=@IDTABLE AND ISPAID=0

	IF(@COUNT =0)
		UPDATE ATABLE SET STATUS= N'TRỐNG'	WHERE ID=@IDTABLE
		UPDATE BILL SET DATECHECKOUT=GETDATE() WHERE ID=@IDBILL
END
GO


CREATE PROC USP_SELECTBILLBYDATE
@DATEIN DATE, @DATEOUT DATE
AS
BEGIN 
	SELECT DISTINCT B.ID AS [SỐ HÓA ĐƠN],B.DATECHECKIN AS[NGÀY VÀO], B.DATECHECKIN AS [NGÀY RA],A.NAME AS[TÊN BÀN],B.TOTALPRICE AS[TỔNG TIỀN]
	FROM BILL B, FOOD F, ATABLE A, BILLINFO BI
	WHERE DATECHECKIN>=@DATEIN AND DATECHECKOUT<=@DATEOUT AND ISPAID=1
	  AND B.ID=BI.IDBILL AND B.IDTABLE=A.ID AND BI.IDFOOD=F.ID
END
GO

CREATE PROC USP_EDITACCOUNT
@USERNAME NVARCHAR(50), @NAME NVARCHAR(100), @PASSWORD NVARCHAR(500),@NEWPASSWORD NVARCHAR(500)
AS
BEGIN
	DECLARE @ISRIGHTPASS INT =0
	SELECT @ISRIGHTPASS=COUNT(*) FROM ACCOUNT WHERE USERNAME=@USERNAME AND PASSWORD=@PASSWORD
	IF(@ISRIGHTPASS=1)
		BEGIN
		IF(@NEWPASSWORD = NULL OR @NEWPASSWORD='')
			
			UPDATE ACCOUNT SET NAME=@NAME WHERE USERNAME=@USERNAME
			
		ELSE
			
			UPDATE ACCOUNT SET NAME=@NAME , PASSWORD=@NEWPASSWORD WHERE USERNAME=@USERNAME
			
		END
	
END
GO