CREATE DATABASE QUANLIBANHANG
GO

USE QUANLIBANHANG
GO



--TABLE
CREATE TABLE ATABLE
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100),
	STATUS NVARCHAR(100) 

)
GO

--FOODCATEGORY
CREATE TABLE FOODCATEGORY
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL,
	
 )
GO
--FOOD
CREATE TABLE FOOD
(	
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100),
	IDCATEGORY INT FOREIGN KEY (IDCATEGORY) REFERENCES FOODCATEGORY(ID),
	PRICE int DEFAULT 0
)
GO
--ACCOUNT
CREATE TABLE ACCOUNT 
(
	USERNAME NVARCHAR(50) NOT NULL PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL DEFAULT 'VANG LAI',
	PASSWORD NVARCHAR(500) NOT NULL,
	KINDOFACC INT NOT NULL
)
GO

--BILL
CREATE TABLE BILL
(
	ID INT IDENTITY PRIMARY KEY,
	DATECHECKIN SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	DATECHECKOUT SMALLDATETIME DEFAULT NULL,
	IDTABLE INT NOT NULL FOREIGN KEY (IDTABLE) REFERENCES ATABLE(ID),
	ISPAID INT NOT NULL
)
go
--BILLINFO
CREATE TABLE BILLINFO
(
	ID INT IDENTITY PRIMARY KEY,
	IDBILL INT NOT NULL FOREIGN KEY(IDBILL) REFERENCES BILL(ID),
	IDFOOD INT NOT NULL FOREIGN KEY (IDFOOD) REFERENCES FOOD(ID),
	SOLUONG INT NOT NULL DEFAULT 0
)
GO
--Tạo Bàn
INSERT INTO ATABLE VALUES (N'BÀN 1', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 2', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 3', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 4', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 5', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 6', N'CÓ NGƯỜI')
INSERT INTO ATABLE VALUES (N'BÀN 7', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 8', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 9', N'TRỐNG')
INSERT INTO ATABLE VALUES (N'BÀN 10', N'TRỐNG')
GO

--TAO CATAGORY
INSERT INTO FOODCATEGORY VALUES(N'Hải Sản')
INSERT INTO FOODCATEGORY VALUES(N'Nông Sản')
INSERT INTO FOODCATEGORY VALUES(N'Thức Uống')
GO
-- THEM MON AN
INSERT INTO FOOD VALUES(N'Mực nướng','1','200000')
INSERT INTO FOOD VALUES(N'Cá Ba Sa Kho','1','100000')
INSERT INTO FOOD VALUES(N'Khoai Lang Nướng','2','10000')
INSERT INTO FOOD VALUES(N'Nước Ngọt','3','7000')
GO
--Them Bill (TEMP)
INSERT INTO BILL VALUES(GETDATE(),NULL,'1','0')
INSERT INTO BILL VALUES(GETDATE(),GETDATE(),'2','1')
GO
--TAI KHOAN MAC DINH
INSERT INTO ACCOUNT VALUES('ADMIN','ADMIN','ADMIN','1')
--Them bill info
INSERT INTO BILLINFO VALUES('1','1','3')
INSERT INTO BILLINFO VALUES('1','2','4')
GO

CREATE PROC USP_insertBillinfo
@idbill int, @idfood int,@count int
AS
BEGIN 
	DECLARE @isEXSISTBILLINFO INT
	DECLARE @foodCount INT
	SELECT @isEXSISTBILLINFO =ID FROM BILLINFO WHERE IDBILL=@idbill AND IDFOOD=@idfood
	SELECT @foodCount=SOLUONG FROM BILLINFO WHERE IDBILL=@idbill AND IDFOOD=@idfood
	IF(@isEXSISTBILLINFO>0)
		BEGIN
		DECLARE @TEMPCOUNT INT =@FOODCOUNT+@COUNT
		IF(@TEMPCOUNT>0)
		BEGIN
			UPDATE BILLINFO SET SOLUONG=@TEMPCOUNT WHERE IDBILL=@IDBILL AND IDFOOD=@idfood
		END
		ELSE
		BEGIN
			DELETE BILLINFO WHERE  IDBILL=@IDBILL AND IDFOOD=@idfood
		END
		END
	ELSE
	BEGIN
	IF(@count <=0)
		BEGIN
		RETURN 1;
		END
	ELSE
	BEGIN
	INSERT BILLINFO
	VALUES (@idbill,@idfood,@count)
	END
	END
END
GO