CREATE DATABASE QUANLIBANHANG
GO

USE QUANLIBANHANG
GO



--TABLE
CREATE TABLE ATABLE
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100),
	STATUS NVARCHAR(100) 

)
GO

--FOODCATEGORY
CREATE TABLE FOODCATEGORY
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL,
	
 )
GO
--FOOD
CREATE TABLE FOOD
(	
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100),
	IDCATEGORY INT FOREIGN KEY (IDCATEGORY) REFERENCES FOODCATEGORY(ID),
	PRICE MONEY DEFAULT 0
)
GO
--ACCOUNT
CREATE TABLE ACCOUNT 
(
	USERNAME NVARCHAR(50) NOT NULL PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL DEFAULT 'VANG LAI',
	PASSWORD NVARCHAR(500) NOT NULL,
	KINDOFACC INT NOT NULL
)
GO

--BILL
CREATE TABLE BILL
(
	ID INT IDENTITY PRIMARY KEY,
	DATECHECKIN SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	DATECHECKOUT SMALLDATETIME,
	IDTABLE INT NOT NULL FOREIGN KEY (IDTABLE) REFERENCES ATABLE(ID),
	ISPAID INT NOT NULL
)
go
--BILLINFO
CREATE TABLE BILLINFO
(
	ID INT IDENTITY PRIMARY KEY,
	IDBILL INT NOT NULL FOREIGN KEY(IDBILL) REFERENCES BILL(ID),
	IDFOOD INT NOT NULL FOREIGN KEY (IDFOOD) REFERENCES FOOD(ID),
	SOLUONG INT NOT NULL DEFAULT 0
)
GO